### PR TITLE
Add skip-missing-hooks option

### PR DESCRIPTION
**Pull request by leplatrem**
Hi there!

We have a use case where we really don't want the hooks to be skipped when they cannot be imported.

So I added an option, with current behaviour as default :)

I'm kinda puzzled with the way I should test this, I would be grateful if you had some insights about the best way to do it!

Thanks, and also thanks for this awesome tool ;)

### CODE REVIEW

**Comment by Natim** [comment]
`TypeError: getboolean() got an unexpected keyword argument 'fallback'` with Python2.7

**Comment by Natim** [comment]
I don't see how the failure in the pypy env are related to that fix.

**Comment by reinout** [comment]
The code itself looks fine. But.... I always dislike extra options on principle :-)

In this case, my thought is "shouldn't this be the default behaviour"? Why would you specify a hook in your `setup.cfg` if you didn't intend to run it? Perhaps because not all developers have installed the necessary library: that's the only reason I can think of right now.

Am I missing something?

My current thoughts:

- Simply fail when a hook is missing. (So: no need for your extra option).

- Or use your extra option, but to make "fail" the *default*. In this case, you *do allow* for missing hooks, but you have to do the extra config work if you're in this corner case. My assumption is that your build tools normally make sure all (dev) dependencies are properly installed, so the hook should really be there.

What are your thoughts?

**Comment by reinout** [comment]
I've re-run the pypy job on travis: it passes now. It already looked like a temporary glitch. We're testing lots of python versions, so small glitches show up more often :-)

**Comment by leplatrem** [comment]
Thanks @reinout for your feedback!

Indeed, I would also be in favor of failing when hook missing! But my intention was to keep the current behavior as default, hence the option.

I will change that immediately then :)

**Comment by leplatrem** [comment]
I updated the code (pypy job might have to be restarted)

**Comment by reinout** [comment]
I've released 6.12.5 with your fix!

**Comment by Natim** [comment]
\o/ thanks

**Pull request merged**
