### PR TITLE
Remove code for support of collective.sdist.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
That package was a backport from distutils for Python 2.5 and earlier,
which we do not support.

@reinout, want to have a look to see if my assumptions are wrong and I break something?

### CODE REVIEW

**Comment by reinout** [comment]
Hey, you removed the 'mregister' command. Wasn't that the "maurits-register" command? :-)

Anyway, looks good to me. Lots of lines removed, which is nice.

**Comment by mauritsvanrees** [comment]
mregister was multiple register I guess. And apparently that was only needed when using collective.dist, as that could not (or did not want to) override the existing register command.

**Comment by reinout** [comment]
I just merged master, can you double-check if I didn't break anything?

After that, you can merge to master and start merging #80, ok? :-)

**Comment by reinout** [comment]
Ah, I *knew* I *had* to have broken something!

**Comment by mauritsvanrees** [comment]
Strange error about not being able to get zope.exceptions from PyPI now, on Python 2.6. I have restarted the job.

**Pull request merged**
