### PR TITLE
signal an error on --no-input and nothing changed yet

### PR DESCRIPTION
**Pull request by do3cc**

### CODE REVIEW

**Comment by do3cc** [comment]
WIP, I have more changes locally to add.

**Comment by mauritsvanrees** [comment]
When we exit explicitly, we should probably always exit with code 1. We were already doing this in most cases.  I have fixed the two remaining cases as part of pull request #139. It is not really related to the rest of the pull request, except that one case was in the middle of some code that I changed a lot, so I thought I might as well fix the other one (in svn) as well.

Did you have other plans with your pull request?

**Comment by do3cc** [comment]
Yes, I wanted to change the log level to error if --no-input is set.
But I still did not make the tests pass with my very new git...
I still plan to and can create a fresh PR just for this. If you fixed the exitcode elsewhere already, you can close this one.

**Comment by reinout** [comment]
Ok, closing this one.

Note that the automatically-answered questions are now always logged at INFO level, so at least you can see what happens if zest.releaser does a `sys.exit(1)` afterwards.

**Comment by do3cc** [comment]
Just fyi,

we are using zest.releaser code embedded in a script of our own. Maybe there will be PRs pushing sys.exit closer to the method called by the script

**Comment by mauritsvanrees** [comment]
Note that I fixed some possible test failures for git svn yesterday, maybe that helps you too.

**Pull request closed without merging**
