### PR TITLE
Using readme 0.6+

### LINKED ISSUE #123: newest release of readme is incompatible with zest.releaser
From readme 0.5.1 to 0.6 the return values of render() have been changed.
Before, it returned two values, now it returns only one value.
It is either the rendered output, or none:
https://github.com/pypa/readme/commit/40caf27bf6f27ad2b9f365202d5baf1c7b381f99#diff-40e9d5b5f74d9d8f5915876cd781c1a9L121

### PR DESCRIPTION
**Pull request by reinout**
Fixes #123

### CODE REVIEW

**Comment by reinout** [comment]
@mauritsvanrees : ok?

**Comment by reinout** [comment]
@mauritsvanrees: are you making a release, too? I don't mind doing it, but I don't want two releases at the same time :-)

**Comment by mauritsvanrees** [comment]
Yes, let me do that.
I am trying one commit to speedup Travis first.

**Comment by mauritsvanrees** [comment]
My Travis changes did not work out.

I have released 5.4.

**Pull request merged**
