### PR TITLE
Add example for restricting the used index servers.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
https://github.com/zestsoftware/zest.releaser/issues/351

### CODE REVIEW

**Comment by reinout** [comment]
I like the change, but travis complains loudly. 2.7 smells like we need an older twine on 2.7.
Do you recognize the 3.8 buildout failure? I've been kinda ignoring the recent buildout error reports as I rarely use it these days...

**Comment by reinout** [comment]
Note: I'm playing with the thought of setting up "github actions" instead of travis. I'm using it for a few work projects now: they spin up real fast.
A docker could also be a nice addition. I'm having problems getting all the tests to pass on my own laptop right now :-)

**Comment by mauritsvanrees** [comment]
It works now locally (on Python 2.7 which I focused on now for the versions), except that the git-svn tests fail, because git-svn itself no longer works on my Mac.
Well, I have a few test failures in `utils.txt` where there is a confusion between an expected SystemExit and a RuntimeError. But `bin/test -t utils.txt` works fine.

Anyway, Travis finally passes.

Switching the tests to use `pip install` and run `pytest` or something like that would be fine for me as well. We now have some automatic grokking.

**Comment by reinout** [comment]
Hurray that you got it working!

**Pull request merged**
