### PR TITLE
Use pypi.org, especially when checking if a package is on PyPI.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
One real code change, the rest is documentation or tests.

Fixes issue #281.

### CODE REVIEW

**Comment by reinout** [comment]
Looks good. There are a few http instead of https links, though. Can you fix those?

Reinout
(Verstuurd vanaf iPhone, dus kort)

**Comment by mauritsvanrees** [comment]
Good catch. Done.

**Comment by mauritsvanrees** [comment]
Travis is moving open source projects from travis-ci.org to travis-ci.com. See [Travis blog](https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps). Apparently this means that currently we do not get any checks from Travis on PRs.

On the github repo there is a new Checks tab, where you can register the repo for the new travis-ci.com, see [blog](https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com). But it seems that then you lose the build history. They will offer migration including history somewhere this quarter, and doing that automatically I think.

It seems strange that this all means that we have no CI currently. Maybe I am missing something.

Anyway, seems fine to merge this PR, as I don't see a chance for possible breakage here, and the tests pass locally. I will merge.

**Comment by mauritsvanrees** [comment]
Released in zest.releaser 6.15.0.

**Pull request merged**
