### PR TITLE
Fixed detecting errors/warnings in output of the 'build' command.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Fixes the final part of issue #420.

### CODE REVIEW

**Review by reinout — APPROVED** [review]
Wow, that's quite some simplification! If it works for you, LGTM :-)

Ping @elisallenens as it simplifies his code a lot, which means there might be corner cases that have been missed.

**Comment by mauritsvanrees** [comment]
I think we are good to go for an alpha release now.
Thanks for your work @elisallenens, and @reinout for all the reviews!

**Comment by reinout** [comment]
Yeah, do the release.

**Comment by elisallenens** [comment]
Oh, this is much better. I didn't really dare touch the show_interesting_lines because I wasn't sure just how it worked together with git and twine, but this is much cleaner than first setting a colour on stderr and then reading the colour.

**Comment by mauritsvanrees** [comment]
I have released 9.0.0a1.

**Pull request merged**
