### PR TITLE
Added bump version command

### PR DESCRIPTION
**Pull request by mauritsvanrees**
This implements issue #160.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Note that this contains the changes done in the open pull request #161 as it needs some of those changes.

**Comment by reinout** [comment]
Looks fine in principle.

I'd add a note in the changelog to say that the exact functionality of bumpversion might change in the next version. Once you start using it for real I suspect there might be one or two small changes.

**Comment by reinout** [comment]
I'll leave merging up to you, too many open intertwined PRs right now.

**Comment by mauritsvanrees** [comment]
I have merged all and released it. I picked version 6.6.0 and set the next version to 6.6.1. So we start using semantic versions ourselves.  Let's see if we like it.

**Pull request merged**
