### PR TITLE
Using importlib instead of pkg_resources for version handling

### PR DESCRIPTION
**Pull request by reinout**

### CODE REVIEW

**Comment by reinout** [comment]
I think there's some docstring output thingy going wrong again. Perhaps the "detached HEAD" message has gotten a bit bigger in git? When comparing the output I don't really discover anything that's wrong except that the `<BLANKLINE>` discovery seems to discover the wrong blank lines in some cases.

@mauritsvanrees, I don't know if you're seein gsomething that's obviously wrong?

**Comment by mauritsvanrees** [comment]
I think the links about writing bdist wheel are extra.

    Showing first few lines...
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib
    ...
    Showing last few lines...
    adding 'tha.example-0.1.dist-info/WHEEL'
    adding 'tha.example-0.1.dist-info/top_level.txt'
    adding 'tha.example-0.1.dist-info/RECORD'
    removing build/bdist.linux-x86_64/wheel
    <BLANKLINE>

**Comment by reinout** [comment]
Yeah, with the test fix from @mauritsvanrees , my PR also works :-) I'm merging it.

@mauritsvanrees : I assume we can do a new release now? I merged your branch as I suspected it was ready, but for safety's sake I'm keeping my finger away from the `fullrelease <enter>` until you give a ping :-)

**Comment by mauritsvanrees** [comment]
Yes, a release is fine. 

Greetings from the Buschenschanksprint in Austria!

**Comment by reinout** [comment]
Buschenschanksprint... Looks nice :-)
Last week I passed by Innsbruck/Brennerpass (by train, of course) on my way to Napoli, so I was a little bit in the neighbourhood.

**Comment by reinout** [comment]
Release (9.2.0) done.

**Pull request merged**
